### ISSUE TITLE
Moving NotFoundHandler to Handler namespace

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-stratigility#1]
Maybe same procedure as in #191 

As the `NotFoundHandler` is technically a `RequestHandler`, I am moving it to the `Handler` namespace instead while marking the `NotFoundHandler` in the `Middleware` namespace as deprecated.

---

Originally posted by @boesing at https://github.com/zendframework/zend-stratigility/pull/192

**Comment by boesing** [comment]
Can be closed in favor of #8

**Comment by boesing** [comment]
Closed due to merging #8
