### ISSUE TITLE
Renaming ErrorHandler to ErrorHandlerMiddleware

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-stratigility#2]
As already mentioned in #190, there is a naming conflict in the `ErrorHandler`.

I had some feedback of trainees which asked me, why the `ErrorHandler` ain't a `RequestHandler`, as its name says.
That made me think about the naming and I realized, its just because of the missing `Middleware` postfix.

However, I'd like to rename the `ErrorHandler` to `ErrorHandlerMiddleware` to avoid future confusions about where the difference between `RequestHandlerInterface` and `MiddlewareInterface` is.

---

Originally posted by @boesing at https://github.com/zendframework/zend-stratigility/pull/191

**Comment by weierophinney** [comment]
/cc @weierophinney @webimpress 

---

Originally posted by @boesing at https://github.com/zendframework/zend-stratigility/pull/191#issuecomment-537071290

**Comment by weierophinney** [comment]
@boesing I think there might be some references to this class in the documentation so we need update it. Other than that LGTM 👍 

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-stratigility/pull/191#issuecomment-537074557

**Comment by boesing** [comment]
Can be closed in favor of #7

**Comment by boesing** [comment]
Closed as this wont be applied.
