### ISSUE TITLE
Add PSR-17 Support

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-stratigility#25]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

Provide support for using [PSR-17](https://www.php-fig.org/psr/psr-17/) response factories instead of a callable for generating error and not found responses. See mezzio/mezzio#81 for details.

**Comment by weierophinney** [comment]
Implemented in #32 (although not yet released)
